name: voluntr-dev-to-main-branch-protection

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ ${GITHUB_HEAD_REF} != dev ]] && ! [[ ${GITHUB_HEAD_REF} =~ ^hotfix/ ]];
          then
            echo "Error: Pull request must come from 'dev' or 'hotfix/' branch"
            exit 1
          fi
